### PR TITLE
Adding a POST endpoint that prints its payload

### PR DESCRIPTION
**Pull request by julia326**
Meant as a start for receiving POST requests from spreadsheet

### CODE REVIEW

**Comment by joshuaellinger** [comment]
Julia -- can you make it return a 400 or 422 if the json content is empty/missing?  I need that for the unit test.

**Comment by joshuaellinger** [comment]
We should add a version like /v1/data/batch

**Comment by julia326** [comment]
The URL actually does include a version, the way this app is set up - so the URL to hit would be `http://127.0.0.1:5000/api/v1/data/batch/`

**Comment by joshuaellinger** [comment]
Cool.  Is that what I should test against?  Does CircleCI actually deploy and run the Flask App?

**Comment by joshuaellinger** [comment]
Basic tests are in.  Runs locally.  Alex probably needs to do some CircleCI config.

**Comment by zachlipton** [comment]
The test fairy comes and deposits this test for future use (depends on #17)

```
def test_post_data_batch(client):
    x = {"test": 123}
    resp = client.post("/api/v1/data/batch/", json=x)
    assert resp.data != None 
    assert resp.status_code == 200
    data = json.loads(resp.data)
    assert "payload" in data
    assert data["payload"] == { "test": 123 }
```

**Pull request merged**
